### ISSUE TITLE
 'MainWindow' object has no attribute 'setWindowflag'

### ISSUE THREAD

**Issue by hhhnano** [vanderkamp/enlighten2#4]
Thank you for sharing the Enlighten2.

I installed Enlighten2 pymol plug successfully at Centos 7 system according to the guide at https://enlighten2.github.io/, howerer, when I launched the plug from Pymol, an error window popup with information "  'MainWindow' object has no attribute 'setWindowflag'  ", I don't know how to fix the issue and ask for your help.
I also installed the required software package Docker.

I switch to another Centos 7 system and install plug, the same issue occured again, Is this a Bug?

Traceback (most recent call last):
  File "/home/xzhfood/software/pymol/lib/python3.7/site-packages/pmg_tk/startup/vanderkamp-enlighten2-pymol-42d0ea7/__init__.py", line 17, in run_plugin_gui
    main_window = MainWindow(window_manager)
  File "/home/xzhfood/software/pymol/lib/python3.7/site-packages/pmg_tk/startup/vanderkamp-enlighten2-pymol-42d0ea7/windows/main.py", line 12, in __init__
    self.setWindowFlag(QtCore.Qt.Tool)
AttributeError: 'MainWindow' object has no attribute 'setWindowFlag'

**Comment by kzinovjev** [comment]
Hi @hhhnano,
This is related to the Enlighten2 PyMOL plugin, not the Enlighten2 python package, so I'm closing the issue.
